{{ if ((.Values.global).hpa).enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "vault.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  minReplicas: {{ .Values.global.hpa.minReplicas }}
  maxReplicas: {{ .Values.global.hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ template "vault.fullname" . }}
  targetCPUUtilizationPercentage: {{ .Values.global.hpa.targetCPUUtilization }}
{{ end }}
